# -*- coding: utf-8 -*-
"""ModAlpha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAFIMy9tRF3spypSwdzmMrCVijA_NpHo
"""

def getAlpha(start, end):
  return[chr(c)+ " = "+str(c) for c in range(ord(start), ord(end)+1)]

class ModAlpha:
  pass