# -*- coding: utf-8 -*-
"""Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YKh_tm-aSsCOuYAR2dVSdTBcip94zMES
"""

a = [100, 200, 300]
s = "If Comrade Napoleon says it, it must be right."

def foo(arg):
    print(f'arg = {arg}')

class Foo:
    pass