# -*- coding: utf-8 -*-
"""SimCal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4w1VK8PIpVLMMmU8hZHoLvk8BvA7rGT
"""

def add(a, b):
  return a+b

def sub(a, b):
  if a > b:
    return a-b
  else:
    return b-a

def mul(a, b):
  return a * b

def div(a,b):
  if b!=0:
   return a/b
  else:
   return "Infinity"
def pow(a, b):
  return a**b
def mod(a, b):
  return a%b